CREATE TABLE IF NOT EXISTS requests (id VARCHAR(36) PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(254) NOT NULL, subject VARCHAR(150) NOT NULL, message VARCHAR(2000) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS outbox (id VARCHAR(36) PRIMARY KEY REFERENCES requests(id), status VARCHAR(20) NOT NULL, error VARCHAR(160));
CREATE TABLE IF NOT EXISTS limits (bucket VARCHAR(64) PRIMARY KEY, window_start BIGINT NOT NULL, hits INT NOT NULL);
CREATE TABLE IF NOT EXISTS submit_lock (id INT PRIMARY KEY);
MERGE INTO submit_lock KEY(id) VALUES(1);
